### ISSUE TITLE
Open question: how to version this API

### ISSUE THREAD

**Issue by yuhonglin** [webmachinelearning/model-loader#25]
If we don't come up with a standard format, an intuitive way is to use the version of the backends to version the API (e.g., TFLite-2.7, TFLite-2.8). But one potential issue is that there may be some OPs that are too dangerous to be exposed to the Web so that we have to disable it. How should we handle this case?

**Comment by yuhonglin** [comment]
@huningxin

**Comment by yuhonglin** [comment]
Also, should we go through a Web Platform review every time we upgrade TFLite and support new OPs? It seems to be necessary. And this also makes me feel that locking down the supported OPs for each version of this API is necessary.

**Comment by anssiko** [comment]
I'm proposing we merge this issue into https://github.com/webmachinelearning/model-loader/issues/28 per https://www.w3.org/2022/03/09-webmachinelearning-minutes.html#t02

**Comment by yuhonglin** [comment]
Close as a duplicate of #28
