### ISSUE TITLE
Open Question: best name of the model loaded by this API

### ISSUE THREAD

**Issue by yuhonglin** [webmachinelearning/model-loader#29]
During implementation, we found the fact that the acronym of "Model Loader" is "ML" same as that of "Machine Learning" causes issues in naming the interfaces. After a discussion with @phoglenix, @wacky6 and @jbingham, there seem to be two choices.

1. Always use the full name "ModelLoader" in names. The goodness is that it is super clear. But it leads to repetitions because we will name the model as "MLModelLoaderModel".
2. One alternative way is to just use "MLModel" as the model name. This will be a good counterpart of "MLGraph" which is used by WebNN API. The main concern with this name is that it may be too generic.

During dev-trial, we will go with choice 2. Our vision is that, if someone (like WebNN) people decide to use the same "MLModel" name, they can consider sharing it. In this way, "MLModel" will be the umbrella interface to cover all the possible cases.

Thanks for discussion/inputs from @phoglenix, @wacky6 and @jbingham.

**Comment by yuhonglin** [comment]
@anssiko

**Comment by huningxin** [comment]
"MLModel" sounds good to me. Thanks for brining this up.

**Comment by anssiko** [comment]
Thanks for thinking of naming in the broader context. The proposal sounds good.

As a reference for the future, you can consult the TAG guidance on naming: https://www.w3.org/TR/design-principles/#naming-is-hard

**Comment by yuhonglin** [comment]
Cool, thank you both.
