### ISSUE TITLE
Use spec-prod to publish spec drafts

### ISSUE THREAD

**Issue by jyasskin** [webmachinelearning/model-loader#9]
As you start working on a more formal specification, it'll be easier to keep the editor's draft up to date if you install the github actions from https://w3c.github.io/spec-prod/ instead of needing to check in the generated index.html with each change.

**Comment by anssiko** [comment]
We should also move from `master` to `main` branch on the same pass.

cc @dontcallmedom

**Comment by dontcallmedom** [comment]
done in #10 and associated repo changes

**Comment by anssiko** [comment]
Thanks @dontcallmedom!

@jbingham here’s the dance needed to sync local copies:

```
$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

Or alternatively clone a new fresh copy.

**Comment by jbingham** [comment]
Thanks!
